"""Shared helpers to read and write site profiles (Markdown files with YAML frontmatter)."""
import glob
import os

import yaml

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
MATRIX = os.path.join(ROOT, "docs", "site-matrix")
PROFILES = os.path.join(MATRIX, "profiles")
LIBRARY = os.path.join(MATRIX, "library.yaml")

# Key order in the written frontmatter; `detected` always goes last.
ORDER = ["id", "name", "country", "status", "phase", "milestones", "registration", "locations", "services",
         "needs", "form_notes", "custom_forms", "integration", "open_items", "notes", "detected"]

HEADER = ("# Site profile. Everything above `detected` is maintained by people (site matrix UI or by hand).\n"
          "# `detected` is generated by scripts/site-profiles/extract.py from the repo: do not edit it.\n")


class _Dumper(yaml.SafeDumper):
    """Matches js-yaml's dump() used by the site matrix page: indented lists, no line folding."""

    def ignore_aliases(self, data):
        return True

    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def _str(dumper, value):
    style = "|" if "\n" in value else ("'" if value.isdigit() else None)
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


_Dumper.add_representer(str, _str)


def profile_path(site_id):
    return os.path.join(PROFILES, site_id + ".md")


def _plain(value):
    """Turn YAML dates into ISO strings so profiles round-trip as JSON."""
    if isinstance(value, dict):
        return {k: _plain(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_plain(v) for v in value]
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return value


def parse(text):
    if not text.startswith("---"):
        return {}, text
    _, fm, body = text.split("---", 2)
    return _plain(yaml.safe_load(fm) or {}), body.lstrip("\n")


def load_profile(site_id):
    path = profile_path(site_id)
    if not os.path.exists(path):
        return {}, ""
    return parse(open(path, encoding="utf-8").read())


def load_all():
    out = []
    for path in sorted(glob.glob(os.path.join(PROFILES, "*.md"))):
        meta, body = parse(open(path, encoding="utf-8").read())
        if meta:
            meta["body"] = body.strip()
            out.append(meta)
    return out


def save_profile(site_id, meta, body=""):
    meta = dict(meta)
    meta.pop("body", None)
    ordered = {k: meta[k] for k in ORDER if k in meta}
    ordered.update({k: v for k, v in meta.items() if k not in ordered and k != "detected"})
    if "detected" in meta:
        ordered.pop("detected", None)
        ordered["detected"] = meta["detected"]
    fm = yaml.dump(ordered, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=100000, default_flow_style=False)
    os.makedirs(PROFILES, exist_ok=True)
    with open(profile_path(site_id), "w", encoding="utf-8") as fh:
        fh.write("---\n" + HEADER + fm + "---\n")
        if body.strip():
            fh.write("\n" + body.strip() + "\n")
