// Read and write site profiles exactly like scripts/site-profiles/profiles.py, so commits from
// the app only touch the lines that changed.
import yaml from "js-yaml";
import type { Profile, SiteChanges } from "./types";

export const ORDER = [
  "id", "name", "country", "status", "phase", "milestones", "registration", "locations", "services",
  "needs", "form_notes", "custom_forms", "integration", "open_items", "notes",
];
export const HEADER =
  "# Site profile. Everything above `detected` is maintained by people (site matrix UI or by hand).\n" +
  "# `detected` is generated by scripts/site-profiles/extract.py from the repo: do not edit it.\n";

export function clone<T>(v: T): T {
  return v == null ? v : JSON.parse(JSON.stringify(v));
}
export function same(a: unknown, b: unknown) {
  return JSON.stringify(a ?? null) === JSON.stringify(b ?? null);
}
export function getPath(o: unknown, path: string): unknown {
  let cur: unknown = o;
  for (const k of path.split(".")) {
    if (cur == null || typeof cur !== "object") return undefined;
    cur = (cur as Record<string, unknown>)[k];
  }
  return cur;
}
export function setPath(o: Record<string, unknown>, path: string, value: unknown) {
  const keys = path.split(".");
  let cur = o;
  for (const k of keys.slice(0, -1)) {
    if (!cur[k] || typeof cur[k] !== "object") cur[k] = {};
    cur = cur[k] as Record<string, unknown>;
  }
  const last = keys[keys.length - 1];
  if (value == null) delete cur[last];
  else cur[last] = value;
}

/** YAML dates become ISO strings, like the Python side. */
function plain(v: unknown): unknown {
  if (v instanceof Date) return v.toISOString().slice(0, 10);
  if (Array.isArray(v)) return v.map(plain);
  if (v && typeof v === "object") return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, plain(x)]));
  return v;
}

export function parseProfile(text: string): { meta: Profile; body: string } {
  text = text.replace(/\r\n/g, "\n");
  if (!text.startsWith("---\n")) return { meta: {} as Profile, body: text };
  const end = text.indexOf("\n---", 3);
  const fm = text.slice(4, end + 1);
  const body = text.slice(end + 4).replace(/^\n+/, "");
  return { meta: (plain(yaml.load(fm)) || {}) as Profile, body };
}

export function renderProfile(meta: Profile, body = ""): string {
  const o: Record<string, unknown> = {};
  for (const k of ORDER) if (k in meta) o[k] = meta[k];
  for (const k of Object.keys(meta)) if (!(k in o) && k !== "detected" && k !== "body") o[k] = meta[k];
  if (meta.detected) o.detected = meta.detected;
  const y = yaml.dump(o, { indent: 2, lineWidth: -1, noRefs: true, sortKeys: false });
  return "---\n" + HEADER + y + "---\n" + (body.trim() ? "\n" + body.trim() + "\n" : "");
}

/** Apply unsaved changes to a profile (never touches `detected`). */
export function applyChanges(meta: Profile, changes: SiteChanges) {
  for (const [k, v] of Object.entries(changes)) {
    if (k === "__new") {
      for (const [f, x] of Object.entries(v as object)) if ((meta as Record<string, unknown>)[f] == null) (meta as Record<string, unknown>)[f] = x;
      continue;
    }
    if (k.startsWith("detected")) continue;
    setPath(meta as Record<string, unknown>, k, clone(v));
  }
  if (meta.milestones) for (const m of Object.keys(meta.milestones)) if (!Object.keys(meta.milestones[m] || {}).length) delete meta.milestones[m];
  return meta;
}

export function expandCodes(list?: string[] | null): string[] {
  const out: string[] = [];
  for (const x of list || []) {
    const m = /^F(\d+)-F(\d+)$/.exec(x);
    if (m) for (let i = +m[1]; i <= +m[2]; i++) out.push("F" + String(i).padStart(2, "0"));
    else out.push(x);
  }
  return out;
}

export function slugify(name: string) {
  return name.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
